name: RegionalOres
version: ${project.version}
main: plugin.bharheinn.regionalores.RegionalOres
api-version: 1.13
authors: [Bharheinn]
description: A plugin that encourages players to travel long distances, trade, and utilise economies to obtain resources.

load: STARTUP

commands:
  oremap:
    description: Gives you a temporary map of the area of the ores.
    usage: /<command> (Requires an empty hand or offhand.)
  oreinfo:
    description: Shows you which ores are being removed or replaced.
    usage: /<command>

permissions:
  regionalores.*:
    description: Gives access to all Regional Ores commands.
    default: true
    children:
      regionalores.oremap: true
      regionalores.oremap.advanced: true
      regionalores.oreinfo: true

  regionalores.oremap:
    description: Allows you to obtain an oremap with /oremap.
    default: true
    children:
      regionalores.oremap.advanced: true

  regionalores.oremap.advanced:
    description: Allows you to see the map scale and current ore rarity with the oremap.
    default: true

  regionalores.oreinfo:
    description: Allows you to obtain information about which ores are being removed or replaced.
    default: true